import type { NextPage } from 'next'
import Head from 'next/head'
import { useForm } from 'react-hook-form'
import If from '../components/If'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {

  const {
    register,
    handleSubmit,
    formState: { errors }
  } = useForm();

  function onSubmit(values: any) {
    console.log(values);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Rule Edit Modal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <form className={styles.form} onSubmit={handleSubmit(onSubmit)}>
        <h1 className={styles.header}>Sign in to Company A</h1>
        <div>
          <input 
            type="text" 
            placeholder="Username or email" 
            {...register('username',  { required: true })} 
          />
          <If condition={errors.username}>
            <p className={styles.field_error}>user name is required</p>
          </If>
        </div>
        <input 
          type="password" 
          placeholder="Password"
          {...register('password', { required: true })} 
        />
        <If condition={errors.password}>
          <p className={styles.field_error}>password is required</p>
        </If>
        <input type="submit" /> 
      </form>
    </div>
  )
}

export default Home
